### ISSUE TITLE
Does not seem to work automatically with Variable Products

### ISSUE THREAD

**Issue by orestiskapar** [jurajk/WooCommerce-Sale-Category#1]
Hello, I've installed the plugin with Wordpress 4.8.1 and I have the following issues with **variable** products:

- Removing a sale price does not remove the product from the 'sale' category (even with reprocessing from WooCommerce -> Intergration)

- Adding a sale price does not automatically add the product in the 'sale' category. To do this I have to process every time from Intergration.

**Comment by jurajk** [comment]
Well, that's pretty possible, since i haven't touched the plugin in two years. If you find a soulution i'll be happy to merge your pull request.

**Comment by Garconis** [comment]
Wish it would work with variations. :(

**Comment by jurajk** [comment]
Good news @KomaGR, @Garconis!

@johnnypea added support for variable products, have fun!
