### ISSUE TITLE
Error on menu save

### ISSUE THREAD

**Issue by FabKos** [jurajk/WooCommerce-Sale-Category#3]
First of all, thank you very much! You're awesome!

When adding the sale category to the menu and hitting the save button I'll get an error like
"Fatal error: Call to a member function is_type() on boolean in [...]wp-content/plugins/WooCommerce-Sale-Category-master/class-wc-integration-sale-category.php on line 64" Can you help me?

Adding a option for further subcategories (waregroups, price-ranges,...) would be great by the way.

All the best

**Comment by FabKos** [comment]
sorry, seems to be a problem when adding a custom css-class and using the max-mega-menu plugin.

**Comment by jurajk** [comment]
Hey @FabKos, i was able to replicate the bug and it's fixed now in v0.2

About the feature request - i have currently no intentions to implement new features or even supporting the plugin, you just caught me with a good mood :)

**Comment by FabKos** [comment]
thank you anyway... lucky me i caught you in that good mood :)
