### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by CelticWebSolutions** [jurajk/WooCommerce-Sale-Category#5]
I've been looking for a simple way for products to be auto added and removed from a category when they are on sale.  I came across this during my search.

Doe sit still work with the latest versions?

**Comment by jurajk** [comment]
Hi, I have no idea, but you can try!

If you tell me more about your usecase, i might be tempted to update the plugin if needed.

**Comment by CelticWebSolutions** [comment]
> Hi, I have no idea, but you can try!
> 
> If you tell me more about your usecase, i might be tempted to update the plugin if needed.

Unfortunately it would appear it does not work.  Loading the page after it’s installed and existing products are imported results in a completely blank page.  

Generally what I wanted was to be able to have a “For sale” products page that had the ability to have filters. While I know it’s easy enough to just show a paginates page of for sale products, that shortcut doesn’t allow for filtering of such things as colour and size of a clothing product.  

So I wanted a plug-in that automatically added and removed products from a set category when they had a for sale price on them.  I thought this would be quite a common request really.  I know you can manually add to a category, I just wanted to automate it. 

There are some other plugins that claim to do this but they don’t actually put for sale products in to a real WooCommerce category.  Which yours did.  

I’ve looked around and found snippets of code too, but again, they don’t seem to work and if they do, they only work with simple products. 

Do you think you’re would be able to work for what I wanted?

**Comment by speedfreakhorror** [comment]
Why not use the default [product] shortcode for this. https://docs.woocommerce.com/document/woocommerce-shortcodes/

there is a On Sale filter

**Comment by CelticWebSolutions** [comment]
Thanks for the suggestion, As mentioned above, I’ve tried that, it doesn’t appear to allow use of the filters easily. As well as that, it wouldn’t be an actual sale category, just a page that has all the for sale items on.

**Comment by CelticWebSolutions** [comment]
Were you able to look to see if your plugin could be made to work with current version on Wordpress please?

**Comment by jonasborneland** [comment]
I've just tried this! Works great! As expected. Thanks for the nice plugin!! I hope you will continue to develop this @jurajk

**Comment by jurajk** [comment]
> I've just tried this! Works great! As expected. Thanks for the nice plugin!! I hope you will continue to develop this @jurajk 

Glad to hear it still works! I will however not continue on this, moved away from wp years ago. But there are already some forks, maybe you'll find luck there :)

**Comment by WildWomble** [comment]
Can confirm it works for Wordpress 5.8 and Woocommerce 5.5.1
