### ISSUE TITLE
Produkty ktore uz nie su v zlave su stale v kategorii zlavnenych

### ISSUE THREAD

**Issue by BalciMirinda** [jurajk/WooCommerce-Sale-Category#6]
Ahoj,
aplikovala som tvoj plugin a vyzera to super. Produkty vsak loadujem cez feed a vsimla som si, ze ked uz skonci zlava (field so zlavovou sumou je prazdny) tieto produkty sa aj tak nachadzaju v kategorii zlavnenych.
Je mozne to nejak zautomatizovat, prebieha tam nejaky cron alebo nieco, co tie produkty vyhodi a naozaj tam zostanu iba tie so sales sumou?

Dakujem

**Comment by jurajk** [comment]
ahoj, to co popisujes by sa malo diat same cez `updated_postmeta` hook. ked skonci zlava, woocommerce upravi produkt tak, aby zlavnena suma ostala prazdna, cim sa zavola dany hook. je vysoko pravdepodobne ze za 6 rokov odkedy tento plugin uzrel svetlo sveta sa zmenilo api a uz to nefunguje. ja uz bohuzial s WP nepracujem par rokov a neviem ti pomoct s updatom. mozes skusit napisat @johnnypea, ci by to nechcel udrziavat.
