### ISSUE TITLE
Is there a chance to have a similar plugin für recent products automatically go into a special category?

### ISSUE THREAD

**Issue by sonjahuber** [jurajk/WooCommerce-Sale-Category#7]
Hi jurajk,
is there a chance to have a similar plugin für recent products automatically go into a special category? Including a time limit - let´s say for 14 days after publishing the product and then being also automatically removed from the special category? You can contact me directly on sonja.huber@mad-addicted.com. Thank you in advance Sonja

**Comment by jurajk** [comment]
Hi @sonjahuber that might be technically possible. However, this plugin is not maintained anymore.
